alert(10 + 10)
alert(1 * 2)
alert(9 + 12)
alert(25 + 25)
alert(10 ** 30)
alert(10 * 10)
alert(15 / 1)
alert(1 + 3)
alert(30 - 2)
alert(10 - 4)

console.log(10 + 10)
console.log(1 * 2)
console.log(9 + 12)
console.log(25 + 25)
console.log(10 ** 30)
console.log(10 * 10)
console.log(15 / 1)
console.log(1 + 3)
console.log(13 - 2)
console.log(10 - 4)


console.log("The Worl Will Be Destroyed in 10 seconds")
console.log("The Worl Will Be Destroyed in 9 seconds")
console.log("The Worl Will Be Destroyed in 8 seconds")
console.log("The Worl Will Be Destroyed in 7 seconds")
console.log("The Worl Will Be Destroyed in 6 seconds")
console.log("The Worl Will Be Destroyed in 5 seconds")
console.log("The Worl Will Be Destroyed in 4 seconds")
console.log("The Worl Will Be Destroyed in 3 seconds")
console.log("The Worl Will Be Destroyed in 2 seconds")
console.log("The Worl Will Be Destroyed in 1 seconds")

alert("The Worl Will Be Destroyed in 10 seconds")
alert("The Worl Will Be Destroyed in 9 seconds")
alert("The Worl Will Be Destroyed in 8 seconds")
alert("The Worl Will Be Destroyed in 7 seconds")
alert("The Worl Will Be Destroyed in 6 seconds")
alert("The Worl Will Be Destroyed in 5 seconds")
alert("The Worl Will Be Destroyed in 4 seconds")
alert("The Worl Will Be Destroyed in 3 seconds")
alert("The Worl Will Be Destroyed in 2 seconds")
alert("The Worl Will Be Destroyed in 1 seconds")